esphome:
  name: inverter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret myPw

ota:
  password: !secret myPw

wifi:
  ssid: !secret ssid
  password: !secret password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inverter Fallback Hotspot"
    password: !secret fallbackpassword

captive_portal:

uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1

modbus:
  flow_control_pin: 4
  id: modbus1

modbus_controller:
  - id: inverter
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter
    id: temp
    name: "Temp"
    address: 3041
    unit_of_measurement: "C"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: ac_power
    name: "AC power"
    address: 3004
    unit_of_measurement: "W"
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: dc_power
    name: "DC power"
    address: 3006
    unit_of_measurement: "W"
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: total_power
    name: "Total power"
    address: 3008
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: today_power
    name: "Power generated today"
    address: 3014
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: yesterday_power
    name: "Power generated yesterday"
    address: 3015
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: month_power
    name: "Power generated this month"
    address: 3010
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: last_month_power
    name: "Power generated last month"
    address: 3012
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: year_power
    name: "Power generated this year"
    address: 3016
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: last_year_power
    name: "Power generated last year"
    address: 3018
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD
